import { Link, Navigate, useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import PublicPageFrame from '../components/PublicPageFrame';
import Seo from '../components/Seo';
import { findPost, knowledgePosts, updatePosts, type ContentPost } from '../content/publicContent';

type ContentKind = 'knowledge' | 'updates';
const kindConfig = { knowledge: { label: '안전 지식', heading: '현장 업무에 쓰이는 안전 지식', intro: '안전 정보를 더 명확하게 찾고 검토하기 위한 기본 원칙과 실무적인 정리 방법을 소개합니다.', posts: knowledgePosts }, updates: { label: '업데이트', heading: 'MeerkatAI 소식과 업데이트', intro: '서비스 운영 원칙과 기능, 콘텐츠 관련 소식을 투명하게 공유합니다.', posts: updatePosts } } as const;
function formatDate(date: string) { return new Intl.DateTimeFormat('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' }).format(new Date(`${date}T00:00:00`)); }
function PostMeta({ post }: { post: ContentPost }) { return <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-[#98989D]"><span>{formatDate(post.publishedAt)}</span><span aria-hidden>·</span><span>{post.readTime}</span>{post.updatedAt && <><span aria-hidden>·</span><span>수정 {formatDate(post.updatedAt)}</span></>}</div>; }

export function PublicContentIndex({ kind }: { kind: ContentKind }) {
  const config = kindConfig[kind]; const basePath = `/${kind}`;
  return <PublicPageFrame language="ko"><Seo title={`MeerkatAI | ${config.label}`} description={config.intro} path={basePath} language="ko" /><div className="mx-auto w-full max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><section className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#00E5FF]">MeerkatAI {config.label}</p><h1 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-5xl">{config.heading}</h1><p className="mt-5 text-base leading-8 text-[#C7C7CC]">{config.intro}</p></section><section className="mt-10 grid gap-5 md:grid-cols-2" aria-label={`${config.label} 목록`}>{config.posts.map((post) => <article key={post.slug} className="flex flex-col rounded-3xl border border-[#2C2C2E] bg-[#1A1A1A] p-6 transition hover:-translate-y-0.5 hover:border-[#00E5FF]/40"><p className="text-xs font-semibold text-[#00E5FF]">{post.category}</p><h2 className="mt-3 text-xl font-semibold leading-7 text-white"><Link to={`${basePath}/${post.slug}`} className="hover:text-[#00E5FF]">{post.title}</Link></h2><p className="mt-3 flex-1 text-sm leading-6 text-[#98989D]">{post.description}</p><div className="mt-6"><PostMeta post={post} /><div className="mt-4 flex flex-wrap gap-2">{post.tags.map((tag) => <span key={tag} className="rounded-full bg-[#00E5FF]/10 px-2.5 py-1 text-xs text-[#00E5FF]">#{tag}</span>)}</div></div></article>)}</section></div></PublicPageFrame>;
}

export function PublicContentDetail({ kind }: { kind: ContentKind }) {
  const { slug } = useParams(); const config = kindConfig[kind]; const post = findPost(config.posts, slug); if (!post) return <Navigate to={`/${kind}`} replace />;
  const path = `/${kind}/${post.slug}`; const structuredData = JSON.stringify({ '@context': 'https://schema.org', '@type': 'Article', headline: post.title, description: post.description, datePublished: post.publishedAt, dateModified: post.updatedAt ?? post.publishedAt, mainEntityOfPage: path, author: { '@type': 'Organization', name: 'MeerkatAI' }, publisher: { '@type': 'Organization', name: 'MeerkatAI' } });
  return <PublicPageFrame language="ko"><Seo title={`${post.title} | MeerkatAI`} description={post.description} path={path} language="ko" /><script type="application/ld+json">{structuredData}</script><article className="mx-auto w-full max-w-3xl px-4 py-10 sm:px-6 lg:px-8"><Link to={`/${kind}`} className="inline-flex text-sm font-medium text-[#00E5FF] hover:underline">← {config.label} 목록</Link><header className="mt-8 border-b border-[#2C2C2E] pb-8"><p className="text-xs font-semibold text-[#00E5FF]">{post.category}</p><h1 className="mt-3 text-3xl font-semibold leading-tight tracking-tight text-white sm:text-5xl">{post.title}</h1><p className="mt-5 text-base leading-8 text-[#C7C7CC]">{post.description}</p><div className="mt-6"><PostMeta post={post} /></div></header><div className="public-article mt-8 text-[15px] leading-8 text-[#C7C7CC]"><ReactMarkdown>{post.body}</ReactMarkdown></div><aside className="mt-10 rounded-2xl border border-[#FF9F0A]/30 bg-[#FF9F0A]/10 p-5 text-sm leading-6 text-[#C7C7CC]"><strong className="text-[#FF9F0A]">안내</strong><p className="mt-2">이 콘텐츠는 일반적인 정보 제공 목적입니다. 실제 현장 적용 전에는 최신 공식 원문과 현장 조건을 확인하고, 필요한 책임자 검토를 거쳐야 합니다.</p></aside></article></PublicPageFrame>;
}
